apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-app
  name: java-app
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      imagePullSecrets:
      - name: credential
      containers:
      - env:
        # - name: BuildVersionId
        #   value: 0.111
        image: azrillana/private-images:#{IMAGE_NAME}#
        name: java-app
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-app
  name: java-app
spec:  
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: java-app
